name: tests

on:
    push:
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        container: ${{ matrix.os == 'ubuntu-latest' && 'mcr.microsoft.com/playwright:v1.52.0' || null }}
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        steps:
            # Fix "Firefox is unable to launch if the $HOME folder isn't owned by the current user"
            # on Ubuntu with the Playwright container.
            - name: Set HOME for Ubuntu
              if: runner.os == 'Linux'
              run: echo "HOME=/root" >> $GITHUB_ENV
            - uses: actions/checkout@v4.1.7
            - uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: '.nvmrc'
            # handle NPM / Node.js repeatedly bricking their npm setup on Windows
            # Note that this won't work if it uses --no-save
            - if: runner.os == 'Windows'
              shell: bash
              run: |
                  npm i npm
            # format package.json is to account for the above `npm i npm` command
            - name: run test
              shell: bash
              run: |
                  npm ci
                  npx playwright install --with-deps
                  npm run format package.json
                  npm run test:all
